[package]
name = "NotVIM"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1.6"
serde_json = "1.0"
colored = "2.0.0"
dirs = "4.0.0"
discord-rich-presence = "0.1.8"
sinner = "0.1"